import Link from "next/link";
import { MarketingShell } from "@/components/landing/MarketingShell";

export default function PrivacyPage() {
  return (
    <MarketingShell>
      <article className="max-w-3xl mx-auto px-6 pt-12 pb-24">
        <header className="mb-12">
          <div className="text-xs uppercase tracking-[0.2em] text-offivex-purple-light mb-3">Legal</div>
          <h1 className="font-display text-5xl md:text-6xl font-bold tracking-tight leading-[0.98] mb-5">
            Privacy Policy
          </h1>
          <p className="text-offivex-text-secondary text-sm">
            Last updated · 2026-05-20 · Operated from Dubai UAE
          </p>
        </header>

        <Intro>
          Offivex (&ldquo;we&rdquo;, &ldquo;us&rdquo;) provides Solana launch tooling on an invite-only basis.
          This policy describes what personal data we collect, how we use it, and the rights you have.
          By using Offivex you agree to the terms below. If you disagree, do not use the service.
        </Intro>

        <Section title="1. Data we collect">
          <p>We collect the minimum required to operate the service:</p>
          <ul className="list-disc pl-5 space-y-2 mt-3">
            <li><b className="text-offivex-text-primary">Application data</b> — Telegram handle, email and project description submitted via <Link href="/apply" className="text-offivex-purple-light hover:text-white underline">/apply</Link>.</li>
            <li><b className="text-offivex-text-primary">Account data</b> — email, hashed password, billing plan, subscription status.</li>
            <li><b className="text-offivex-text-primary">Encrypted wallet payloads</b> — your wallet private keys are encrypted client-side with your password. We store only the encrypted ciphertext; we cannot decrypt it.</li>
            <li><b className="text-offivex-text-primary">Usage metadata</b> — IP address (for rate-limiting and fraud prevention), API call counts, feature usage aggregates.</li>
            <li><b className="text-offivex-text-primary">Payment data</b> — crypto only (SOL, USDC-Solana, USDT-TRC20). Invoices generated by NOWPayments or paid directly to a verified Offivex wallet. We see only the source wallet address and the on-chain transaction signature.</li>
          </ul>
        </Section>

        <Section title="2. How we use your data">
          <ul className="list-disc pl-5 space-y-2">
            <li>Operate the service, authenticate you, and bill your subscription.</li>
            <li>Review applications and contact you on Telegram or email about your account.</li>
            <li>Detect abuse (rate-limit by IP, identify suspicious patterns).</li>
            <li>Comply with legal obligations in our jurisdiction (UAE) and respond to lawful requests.</li>
            <li>Improve features and infrastructure performance (aggregate, anonymized telemetry).</li>
          </ul>
          <p className="mt-3"><b className="text-offivex-text-primary">We do not sell your personal data.</b></p>
        </Section>

        <Section title="3. Third-party processors">
          <ul className="list-disc pl-5 space-y-2">
            <li><b className="text-offivex-text-primary">NOWPayments</b> — crypto invoice generation and confirmation (EE).</li>
            <li><b className="text-offivex-text-primary">Telegram</b> — application form notifications via bot API.</li>
            <li><b className="text-offivex-text-primary">Resend / Postmark</b> — transactional email delivery.</li>
            <li><b className="text-offivex-text-primary">Helius</b> — Solana RPC infrastructure (your transactions go through their nodes).</li>
            <li><b className="text-offivex-text-primary">BrightData / Smartproxy</b> — residential proxy rotation (no personal data shared).</li>
            <li><b className="text-offivex-text-primary">hCaptcha</b> — bot prevention on auth flows.</li>
          </ul>
          <p className="mt-3">Each processor is contractually bound to GDPR / UAE PDPL standards.</p>
        </Section>

        <Section title="4. Storage & security">
          <ul className="list-disc pl-5 space-y-2">
            <li>Encrypted wallet payloads at rest using AES-256-GCM with Argon2id-derived keys.</li>
            <li>TLS in transit (HTTPS-only, HSTS enforced).</li>
            <li>Database backups encrypted and stored in geographically separate UAE region.</li>
            <li>Production access restricted to two named operators with hardware 2FA.</li>
            <li>Independent annual penetration test (most recent: 2026-Q1).</li>
          </ul>
        </Section>

        <Section title="5. Your rights">
          <p>Depending on your jurisdiction, you may have rights to:</p>
          <ul className="list-disc pl-5 space-y-2 mt-3">
            <li>Access the personal data we hold on you.</li>
            <li>Correct inaccurate data.</li>
            <li>Delete your account and associated data (subject to legal retention).</li>
            <li>Export your data in machine-readable form.</li>
            <li>Object to specific uses or withdraw consent.</li>
          </ul>
          <p className="mt-3">Email <a href="mailto:privacy@offivex.io" className="text-offivex-purple-light hover:text-white underline">privacy@offivex.io</a> with the subject &ldquo;Data request&rdquo; — we reply within 14 days.</p>
        </Section>

        <Section title="6. Retention">
          <ul className="list-disc pl-5 space-y-2">
            <li>Application form data: 12 months after rejection / indefinitely while account active.</li>
            <li>Encrypted wallet payloads: retained while account is active; purged 90 days after cancellation.</li>
            <li>Billing records: 7 years (UAE tax law).</li>
            <li>Server logs (IP, request metadata): 90 days.</li>
          </ul>
        </Section>

        <Section title="7. Cookies">
          <p>Offivex uses strictly necessary cookies only — session token and CSRF token after sign-in. No advertising, no third-party analytics on the dashboard.</p>
          <p className="mt-3">The marketing site (offivex.io) may use Plausible Analytics (privacy-friendly, no PII, no cookies).</p>
        </Section>

        <Section title="8. International transfers">
          <p>Servers are hosted in the UAE. NOWPayments / Helius / proxies may process data outside the UAE under standard contractual clauses.</p>
        </Section>

        <Section title="9. Children">
          <p>Offivex is not directed at users under 18. If you are under 18, do not use the service.</p>
        </Section>

        <Section title="10. Changes to this policy">
          <p>Material changes are emailed to active subscribers at least 30 days before taking effect. Minor edits (typos, clarifications) may be made without notice.</p>
        </Section>

        <Section title="11. Contact">
          <p>
            Privacy questions, complaints, or data-subject requests :
            <a href="mailto:privacy@offivex.io" className="text-offivex-purple-light hover:text-white underline ml-1">privacy@offivex.io</a>
          </p>
          <p className="mt-3">Postal address available on request — we do not publish it to deter solicitations.</p>
        </Section>
      </article>
    </MarketingShell>
  );
}

function Intro({ children }: { children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-6 mb-12 text-sm text-offivex-text-secondary leading-relaxed">
      {children}
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="font-display text-xl md:text-2xl font-semibold text-white mb-4 tracking-tight">{title}</h2>
      <div className="text-sm text-offivex-text-secondary leading-relaxed space-y-3">{children}</div>
    </section>
  );
}
