[package]
name = "cresus-core"
version.workspace = true
edition.workspace = true

[dependencies]
solana-sdk = "=2.1.15"
solana-client = "=2.1.15"
spl-token = "7"
mpl-token-metadata = "5"
rayon = "1.10"
tokio.workspace = true
tokio-tungstenite = "0.24"
reqwest = { version = "0.12", features = ["json", "multipart"] }
serde.workspace = true
serde_json.workspace = true
bincode = "1"
bs58 = "0.5"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
tokio-rusqlite = "0.5"
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
rand = "0.8"
zeroize = "1.7"
dashmap = "6"
futures-util = "0.3"

cresus-crypto = { path = "../cresus-crypto" }
cresus-db = { path = "../cresus-db" }
