[package]
name = "offivex-core"
version.workspace = true
edition.workspace = true

[dependencies]
solana-sdk = "=2.1.15"
solana-client = "=2.1.15"
solana-account-decoder = "=2.1.15"
solana-transaction-status = "=2.1.15"
spl-token = { version = "7", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "4", features = ["no-entrypoint"] }
mpl-token-metadata = "5"
rayon = "1.10"
tokio.workspace = true
tokio-tungstenite = "0.24"
reqwest = { version = "0.12", features = ["json", "multipart"] }
httpdate = "1"
serde.workspace = true
serde_json.workspace = true
bincode = "1"
base64 = "0.21"
bs58 = "0.5"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
tokio-rusqlite = "0.5"
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
rand = "0.8"
zeroize = "1.7"
dashmap = "6"
futures-util = "0.3"
moka = { version = "0.12", features = ["future"] }
# Phase 5 — SLIP-0010 ed25519 HD derivation for invoice addresses
hmac = "0.12"
sha2 = "0.10"

offivex-crypto = { path = "../offivex-crypto" }
offivex-db = { path = "../offivex-db" }

[dev-dependencies]
tempfile = "3"
